apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass
  annotations:
    build.knative.dev/docker-0: https://index.docker.io/v1/
type: kubernetes.io/basic-auth
stringData:
  # Using cleartext not base64 encoded version. BECAREFUL not to commit real credentials to github public repos! :-)
  username: <Change to my dockerhub Id>
  password: <Change to my dockerhub password>
